language: go

go:
  - 1.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libglew-dev # required by headless-gl.
      - libglu1-mesa-dev
      - libgles2-mesa-dev
      - libxrandr-dev
      - libxcursor-dev
      - libxinerama-dev
      - libxi-dev
      - libopenal-dev
      - libalut-dev
      - libxxf86vm-dev

before_install:
  - export NODE_PATH=$(npm config get prefix)/lib/node_modules
  - npm install --global gl

install:
  - go get -t -v ./...
  - go get github.com/gopherjs/gopherjs
  - go get github.com/gopherjs/webgl

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3

script:
  - go build -v ./...
  - gopherjs build -v github.com/hajimehoshi/ebiten/examples/blocks
  - go test -v ./...

# Looks like testing GL on node is hard.
# - gopherjs test -v github.com/hajimehoshi/ebiten github.com/hajimehoshi/ebiten/internal/graphics

notifications:
  email:
    recipients:
      - hajimehoshi@gmail.com
